POST http://localhost:3001/songs
Content-Type: application/json

{
    "title": "Interaksi",
    "artist": "Tulus",
    "url": "https://open.spotify.com/track/32Pdf9eyXDEMoClEJW6yYP?si=0a6d72f7f78e4a51",
    "img_url": "https://i.scdn.co/image/ab67616d0000b273b55d26c578e30129b0a7e86e"
}

###

POST http://localhost:3001/songs
Content-Type: application/json

{
    "title": "One Thing",
    "artist": "One Direction",
    "url": "https://open.spotify.com/track/5G2c6FsfTzgYUzageCmfXY?si=fefb20cc092d41e1",
    "img_url": "https://i.scdn.co/image/ab67616d0000b2734a5584795dc73860653a9a3e"
}

###

GET http://localhost:3001/songs/sorted?favsong=asc
Content-Type: application/json

###

GET http://localhost:3001/songs
Content-Type: application/json